import 'dart:convert';
import 'disc_model.dart';
import 'package:easy_localization/easy_localization.dart';


final List<DiscQuestion> discQuestions = [

  DiscQuestion(
    group: 1,
    text: "Easy-going, Agreeable".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 1,
    text: "Trusting, believing in others".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 1,
    text: "Adventurous, Risk taker".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 1,
    text: "Tolerant, Respectful".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 2,
    text: "Soft spoken, Reserved".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 2,
    text: "Optimistic, Visionary".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 2,
    text: "Center of attention, Sociable".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 2,
    text: "Peacemaker, Bring harmony".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 3,
    text: "Encourage others".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 3,
    text: "Strive for perfection".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 3,
    text: "Be part of the team".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 3,
    text: "Want to establish goals".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 4,
    text: "Become frustrated".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 4,
    text: "Keep my feelings inside".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 4,
    text: "Tell my side of the story".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 4,
    text: "Stand up to opposition".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 5,
    text: "Lively, Talkative".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 5,
    text: "Fast paced, Determined".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 5,
    text: "Try to maintain balance".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 5,
    text: "Try to follow the rules".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 6,
    text: "Manage time effectively".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 6,
    text: "Often rushed, feel pressured".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 6,
    text: "Social things are important".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 6,
    text: "Like to finish what I start".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 7,
    text: "Resist sudden change".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 7,
    text: "Tend to over promise".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 7,
    text: "Withdraw under pressure".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 7,
    text: "Not afraid to fight".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 8,
    text: "A good encourager".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 8,
    text: "A good listener".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 8,
    text: "A good analyser".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 8,
    text: "A good delegator".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 9,
    text: "Results are what matter".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 9,
    text: "Do it right, Accuracy counts".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 9,
    text: "Make it enjoyable".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 9,
    text: "Lets do it together".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 10,
    text: "Will do without, Self-controlled".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 10,
    text: "Will buy on impulse".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 10,
    text: "Will wait, No pressure".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 10,
    text: "Will spend on what I want".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 11,
    text: "Friendly, Easy to be with".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 11,
    text: "Unique, Bored by routine".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 11,
    text: "Actively change things".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 11,
    text: "Want things exact".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 12,
    text: "Non-confrontational, Giving in".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 12,
    text: "Overloaded with detail".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 12,
    text: "Changes at the last minute".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 12,
    text: "Demanding, Abrupt".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 13,
    text: "Want advancement".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 13,
    text: "Satisfied with things, Content".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 13,
    text: "Openly display feelings".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 13,
    text: "Humble, Modest".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 14,
    text: "Cool, Reserved".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 14,
    text: "Happy, Carefree".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 14,
    text: "Pleasing, Kind".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 14,
    text: "Bold, Daring".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 15,
    text: "Spend quality time with others".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 15,
    text: "Plan for the future, Be prepared".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 15,
    text: "Travel to new adventures".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 15,
    text: "Receive rewards for goals met".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 16,
    text: "Rules need to be challenged".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 16,
    text: "Rules make it fair".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 16,
    text: "Rules make it boring".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 16,
    text: "Rules make it safe".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 17,
    text: "Education, Culture".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 17,
    text: "Achievements, Awards".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 17,
    text: "Safety, Security".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 17,
    text: "Social, Group Gatherings".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 18,
    text: "Take charge, Direct approach".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 18,
    text: "Outgoing, Adventurous".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 18,
    text: "Predictable, Consistent".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 18,
    text: "Cautious, Careful".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 19,
    text: "Not easily defeated".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 19,
    text: "Will do as told, Follows leader".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 19,
    text: "Excitable, Cheerful".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 19,
    text: "Want things orderly, Neat".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 20,
    text: "I will lead them".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 20,
    text: "I will follow through".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 20,
    text: "I will persuade them".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 20,
    text: "I will get the facts".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 21,
    text: "Think of others first".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 21,
    text: "Competitive, Like a challenge".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 21,
    text: "Optimistic, Positive".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 21,
    text: "Logical thinker, Systematic".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 22,
    text: "Please others, Agreeable".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 22,
    text: "Laugh out loud, Animated".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
  ),
  DiscQuestion(
    group: 22,
    text: "Courageous, Bold".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 22,
    text: "Quiet, Reserved".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 23,
    text: "Want more authority".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 23,
    text: "Want new opportunities".tr(),
    most: {'s': 0, 'd': 0, 'i': 1, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 23,
    text: "Avoid any conflict".tr(),
    most: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 23,
    text: "Want clear directions".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 24,
    text: "Reliable, Dependable".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
    least: {'s': 1, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 24,
    text: "Creative, Unique".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
  ),
  DiscQuestion(
    group: 24,
    text: "Bottom line, Results oriented".tr(),
    most: {'s': 0, 'd': 1, 'i': 0, 'c': 0},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
  DiscQuestion(
    group: 24,
    text: "Hold high standards, Accurate".tr(),
    most: {'s': 0, 'd': 0, 'i': 0, 'c': 1},
    least: {'s': 0, 'd': 0, 'i': 0, 'c': 0},
  ),
];