// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
///
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHSydBEFiuzlgXuuVwL6rTHL0ItwwM3x8',
    appId: '1:184915145835:web:658ac711eec438046dad2e',
    messagingSenderId: '184915145835',
    projectId: 'disclystics',
    authDomain: 'disclystics.firebaseapp.com',
    storageBucket: 'disclystics.firebasestorage.app',
    measurementId: 'G-T4KR6B6Y96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvJXPq-pwFvvFI_r8POVBIyJqtDeMmh6Y',
    appId: '1:184915145835:android:85234dcec9dc28746dad2e',
    messagingSenderId: '184915145835',
    projectId: 'disclystics',
    storageBucket: 'disclystics.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQAw_KQANBUFUyEUKYDXS3VxI2k3mu0qc',
    appId: '1:184915145835:ios:96037426a4e8d1c86dad2e',
    messagingSenderId: '184915145835',
    projectId: 'disclystics',
    storageBucket: 'disclystics.firebasestorage.app',
    androidClientId:
        '184915145835-8e9teiptj0d83bsp6cs65e42lca6di3j.apps.googleusercontent.com',
    iosClientId:
        '184915145835-is0v64fi3pr3nedc4h4n39tsgbqueuiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.disclystics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQAw_KQANBUFUyEUKYDXS3VxI2k3mu0qc',
    appId: '1:184915145835:ios:96037426a4e8d1c86dad2e',
    messagingSenderId: '184915145835',
    projectId: 'disclystics',
    storageBucket: 'disclystics.firebasestorage.app',
    androidClientId:
        '184915145835-8e9teiptj0d83bsp6cs65e42lca6di3j.apps.googleusercontent.com',
    iosClientId:
        '184915145835-is0v64fi3pr3nedc4h4n39tsgbqueuiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.disclystics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHSydBEFiuzlgXuuVwL6rTHL0ItwwM3x8',
    appId: '1:184915145835:web:74a7ea3fada77ba16dad2e',
    messagingSenderId: '184915145835',
    projectId: 'disclystics',
    authDomain: 'disclystics.firebaseapp.com',
    storageBucket: 'disclystics.firebasestorage.app',
    measurementId: 'G-0SZHVSZ062',
  );
}
